global:
  scrape_interval: 15s # Set the interval at which Prometheus will scrape the targets

scrape_configs:
  - job_name: 'api-orders'
    static_configs:
      - targets: ['api-orders:5001']

  - job_name: 'webapp'
    static_configs:
      - targets: ['metrics-server:3002']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
